using System;
using System.Collections.Generic;
using System.Net.Http;
using Raven.Client.Documents.Conventions;
using Raven.Client.Http;
using Raven.Client.Json;
using Raven.Client.Json.Serialization;
using Raven.Client.Util;
using Sparrow.Json;
using Sparrow.Json.Parsing;

namespace Raven.Client.Documents.Operations.AI.Agents;
public class StartChatOperation<TSchema> : IMaintenanceOperation<ChatResult<TSchema>> where TSchema : new()
{
    private readonly string _name;
    private readonly string _prompt;
    private readonly Dictionary<string, object> _parameters;

    public StartChatOperation(string agentName, string prompt, Dictionary<string, object> parameters = null)
    {
        ValidationMethods.AssertNotNullOrEmpty(agentName, nameof(agentName));
        ValidationMethods.AssertNotNullOrEmpty(prompt, nameof(prompt));

        _name = agentName;
        _prompt = prompt;
        _parameters = parameters;
    }

    public RavenCommand<ChatResult<TSchema>> GetCommand(DocumentConventions conventions, JsonOperationContext context)
    {
        return new StartChatOperationCommand(_name, _prompt, _parameters, conventions);
    }

    internal sealed class StartChatOperationCommand : RavenCommand<ChatResult<TSchema>>
    {
        private readonly string _name;
        private readonly string _prompt;
        private readonly Dictionary<string, object> _parameters;
        private readonly DocumentConventions _conventions;

        public StartChatOperationCommand(string agentName, string prompt, Dictionary<string, object> parameters, DocumentConventions conventions)
        {
            _name = agentName;
            _prompt = prompt;
            _parameters = parameters;
            _conventions = conventions;
        }
        public override bool IsReadRequest => false;
        public override HttpRequestMessage CreateRequest(JsonOperationContext ctx, ServerNode node, out string url)
        {
            url = $"{node.Url}/databases/{node.Database}/ai/agent/start?agent={Uri.EscapeDataString(_name)}";
            var body = new StartChatBody { Prompt = _prompt, Parameters = _parameters };


            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Post,
                Content = new BlittableJsonContent(async stream =>
                {
                    await ctx.WriteAsync(stream, ctx.ReadObject(body.ToJson(),"chat-params")).ConfigureAwait(false);
                }, _conventions)
            };

            return request;
        }

        public override void SetResponse(JsonOperationContext context, BlittableJsonReaderObject response, bool fromCache)
        {
            if (response == null)
                ThrowInvalidResponse();

            response.TryGet(nameof(ChatResult<TSchema>.Usage), out BlittableJsonReaderObject usage);
            response.TryGet(nameof(ChatResult<TSchema>.Response), out BlittableJsonReaderObject result);
            response.TryGet(nameof(ChatResult<TSchema>.ChatId), out string chatId);

            Result = new ChatResult<TSchema>
            {
                ChatId = chatId,
                Usage = JsonDeserializationClient.AiUsage(usage),
                Response = _conventions.Serialization.DefaultConverter.FromBlittable<TSchema>(result, chatId)
            };
        }
    }
}

internal class StartChatBody : IDynamicJson
{
    public Dictionary<string, object> Parameters { get; set; }
    public string Prompt { get; set; }
    public DynamicJsonValue ToJson()
    {
        return new DynamicJsonValue
        {
            [nameof(Parameters)] = DynamicJsonValue.Convert(Parameters),
            [nameof(Prompt)] = Prompt
        };
    }
}

/// <summary>
/// Represents the result of an AI chat interaction, including the chat ID, response, and usage metadata.
/// </summary>
/// <typeparam name="T">The type of the response returned by the AI agent.</typeparam>
public class ChatResult<T>
{
    /// <summary>
    /// The unique identifier of the chat session.
    /// Will be <c>null</c> if no chat was created — typically when the <c>Persistence</c> property in the agent configuration is <c>null</c>.
    /// </summary>
    public string ChatId { get; set; }

    /// <summary>
    /// The response returned by the AI agent.
    /// </summary>
    public T Response { get; set; }

    /// <summary>
    /// Information about the usage of the AI model during this interaction (e.g., tokens used).
    /// </summary>
    public AiUsage Usage { get; set; }
}

/// <summary>
/// Represents usage statistics for an AI interaction, including token counts for billing, caching, and optimization purposes.
/// </summary>
public class AiUsage : IDynamicJsonValueConvertible
{
    /// <summary>
    /// The number of tokens used in the prompt sent to the AI.
    /// </summary>
    public int PromptTokens { get; set; }

    /// <summary>
    /// The number of tokens generated by the AI in the response.
    /// </summary>
    public int CompletionTokens { get; set; }

    /// <summary>
    /// The total number of tokens used in the interaction (prompt + completion).
    /// </summary>
    public int TotalTokens { get; set; }

    /// <summary>
    /// The number of tokens retrieved from cache instead of being recomputed by the AI.
    /// Useful for measuring optimization impact.
    /// </summary>
    public int CachedTokens { get; set; }

    internal void UpdateFrom(BlittableJsonReaderObject json)
    {
        json.TryGet("prompt_tokens", out int promptTokens);
        json.TryGet("completion_tokens", out int completionTokens);
        json.TryGet("total_tokens", out int totalTokens);

        PromptTokens += promptTokens;
        CompletionTokens += completionTokens;
        TotalTokens += totalTokens;

        if (json.TryGet("prompt_tokens_details", out BlittableJsonReaderObject promptDetails))
        {
            if(promptDetails.TryGet("cached_tokens", out int cachedTokens))
                CachedTokens += cachedTokens;
        }
    }

    public DynamicJsonValue ToJson()
    {
        return new DynamicJsonValue
        {
            [nameof(PromptTokens)] = PromptTokens,
            [nameof(CompletionTokens)] = CompletionTokens,
            [nameof(TotalTokens)] = TotalTokens,
            [nameof(CachedTokens)] = CachedTokens,
        };
    }

    internal  void Write(AsyncBlittableJsonTextWriter writer)
    {
        writer.WriteStartObject();

        writer.WritePropertyName(nameof(PromptTokens));
        writer.WriteInteger(PromptTokens);
        writer.WriteComma();
        
        writer.WritePropertyName(nameof(CompletionTokens));
        writer.WriteInteger(CompletionTokens);
        writer.WriteComma();
        
        writer.WritePropertyName(nameof(TotalTokens));
        writer.WriteInteger(TotalTokens);
        writer.WriteComma();
        
        writer.WritePropertyName(nameof(CachedTokens));
        writer.WriteInteger(CachedTokens);
        writer.WriteEndObject();
    }
}
